backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "content/blog" 
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: fields
    label: Fields
    files:
      - label: Select
        name: select
        file: config/select.yml
        fields:
          - label: "Align Content"
            name: "align"
            widget: "select"
            options: ["left", "center", "right"]
          - label: "City"
            name: "airport-code"
            widget: "select"
            options:
              - { label: "Chicago", value: "ORD" }
              - { label: "Paris", value: "CDG" }
              - { label: "Tokyo", value: "HND" }

