backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/img

collections:
  - name: "blog" 
    label: "Blog" 
    folder: "content/blog"
    category: tag1
    create: true 
    fields: 
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: settings
    label: Settings
    category: tag1
    files:
      - label: Theme settings
        name: themesettings
        file: config/themesettings.yml
        fields:
          - label: "Color of your thmeme"
            name: "themecolor"
            widget: "string"
          - label: "Font size"
            name: "fontsize"
            widget: "string"
            
      - label: GA settings
        name: gasettings
        file: config/gasettings.yml
        fields:
          - label: "Please enter your GA code"
            name: "gacode"
            widget: "string"


  - name: psettings
    label: Personal Settings
    category: tag1
    files:
      - label: Bio
        name: bio
        file: content/bio.yml
        fields:
          - {label: "Bio", name: "bio", widget: "markdown"}
      - label: Sport
        name: sport
        file: config/sport.yml
        fields:
          - {label: "Favorite team", name: "favteam", widget: "string"}
          - {
            label: "Ref blogs", 
            name: "refblogs", 
            widget: "relation", 
            collection: "blog", 
            search_fields: ["title"], 
            value_fields: ["title"],
            multiple: true
            }
